### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by brianoh** [wjayesh/companion-streams#1]
Error is as follows:
"Not Now" pressed in response to "Ready to answer a few questions".

To quit, press "q".
E/flutter (11237): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(no such column: q1 (code 1): , while compiling: UPDATE Client SET id = ?, first_name = ?, q1 = NULL, q2 = NULL, q3 = NULL, q1old = NULL, q2old = NULL, q3old = NULL, value = ?, notDone1 = ?, notDone2 = ?, notDone3 = ?, answered = ?, hour = NULL, progress1 = NULL, progress2 = NULL, show1 = ?, show2 = ? WHERE id = ?) sql 'UPDATE Client SET id = ?, first_name = ?, q1 = NULL, q2 = NULL, q3 = NULL, q1old = NULL, q2old = NULL, q3old = NULL, value = ?, notDone1 = ?, notDone2 = ?, notDone3 = ?, answered = ?, hour = NULL, progress1 = NULL, progress2 = NULL, show1 = ?, show2 = ? WHERE id = ?' args [3, brianoh, false, false, false, false, true, false, false, 3]}
E/flutter (11237): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11)
E/flutter (11237): <asynchronous suspension>

**Comment by wjayesh** [comment]
This has been resolved. There was a mismatch in the order of SQL statements in the Database.dart class.
